### ISSUE TITLE
about order 

### ISSUE THREAD

**Issue by ThirdPrince** [enbandari/PortableAndroidHandler#1]
HandlerThread handlerThread = new HandlerThread("Working");
        handlerThread.start();
        for(int i = 0;i< 400;i++){
            BaseTestHandler handler = new BaseTestHandler( handlerThread.getLooper());
            Message message = new Message();
            message.obj = "OK"+i;
            handler.sendMessage(message);
        }

为何不是按照顺序输出，我并没有延迟的情况下。

**Comment by bennyhuo** [comment]
消息是按照时间顺序消费的。你可以按照这个思路分析一下。
