### ISSUE TITLE
message  顺序不一样

### ISSUE THREAD

**Issue by ThirdPrince** [enbandari/PortableAndroidHandler#2]
getDelay 方法里改成 System.nanoTime() 就OK？

**Comment by bennyhuo** [comment]
只要时间一样，执行顺序就取决于优先级队列的排序算法了。改成nano只不过是降低了时间一致的可能性。实际上这块儿确实没有对时间相同的消息的执行有明确定义。

**Comment by ThirdPrince** [comment]
HandlerThread handlerThread = new HandlerThread("workingThread");
        handlerThread.start();
        TestHandler testHandler = new TestHandler(handlerThread.getLooper());
        for (int i = 0;i < 1000; i++){
            Message msg = Message.obtain();
            msg.obj = "i+"+i;
            testHandler.sendMessage(msg);
        }
这样的代码输出 msg  不是按顺序的。我改了两处 输出就有顺序了，一个是 Message 中的getDelay 把时间改成nanotime,一个是Handler 的 sendMessageDelayed 时间改成 nano。Actually ，只要时间一样，执行顺序就取决于优先级队列的排序算法了。改成nano只不过是降低了时间一致的可能性。实际上这块儿确实没有对时间相同的消息的执行有明确定义。这句话我没怎么懂。。。。。。

**Comment by bennyhuo** [comment]
你的这个用例，很多消息是不是时间在毫秒级都一样？如果是的话，那比较的时候确实无法区分出哪个在前，这就取决于内部用的优先级队列的排序逻辑了。

**Comment by ThirdPrince** [comment]
哦，明白了。感谢benny。

**Comment by bennyhuo** [comment]
😁
